autosearch.config-path=config.yaml
autosearch.model-path=${user.home}/.autosearch/model/autosearch-embed.onnx
autosearch.tokenizer-path=${user.home}/.autosearch/model/
autosearch.embeddings-path=${user.home}/.autosearch/embeddings/data-items.json
