autosearch.config-path=examples/health-workforce/config.yaml
autosearch.model-path=${user.home}/.autosearch/model/autosearch-embed.onnx
autosearch.tokenizer-path=${user.home}/.autosearch/model/
autosearch.embeddings-path=${user.home}/.autosearch/embeddings/data-items.json
autosearch.corpus-path=${user.home}/.autosearch/corpus/corpus.json
autosearch.ui-config-path=${user.home}/.autosearch/corpus/corpus-ui.json
